In [14]:
def distance(str1, str2):
  d=dict()
  for i in range(len(str1)+1):
     d[i]=dict()
     d[i][0]=i
  for i in range(len(str2)+1):
     d[0][i] = i
  for i in range(1, len(str1)+1):
     for j in range(1, len(str2)+1):
        d[i][j] = min(d[i][j-1]+1, d[i-1][j]+1, d[i-1][j-1]+(not str1[i-1] == str2[j-1]))
  print(d)
  return d[len(str1)][len(str2)]

In [7]:
distance('hola', 'saas')

{0: {0: 0, 1: 1, 2: 2, 3: 3, 4: 4}, 1: {0: 1, 1: 1, 2: 2, 3: 3, 4: 4}, 2: {0: 2, 1: 2, 2: 2, 3: 3, 4: 4}, 3: {0: 3, 1: 3, 2: 3, 3: 3, 4: 4}, 4: {0: 4, 1: 4, 2: 3, 3: 3, 4: 4}}


4

In [38]:
import numpy as np 
def matriz(term, ref):
   """
   Metodo dado en el boletin
   """
   vref = np.array(list(ref))
   return np.vstack([vref != letter for letter in term]) + 0


def levenshtein(term, ref):
   """
   Calcula la distancia de Levenshtein entre las cadenas term y ref
   """
   mat = matriz(term, ref)
   res = np.zeros(shape=(len(term)+1,len(ref)+1))
   for i in range(0,len(term)+1):
      for j in range(0,len(ref)+1):
            if i==0 or j==0:
               res[i,j] = res[i,j] + i + j
            else:
               res[i,j] =min(
                  mat[i-1,j-1] + res[i-1,j-1],
                  1 + res[i-1,j],
                  1 + res[i,j-1]
               )
               
   return res[len(term),len(ref)]

In [70]:
for term,ref in [("campos","ejemplo"), ("reconocibles","irreconocible"), ("hola", "holas")]:
    print(term,ref,damerau_levenstein(term,ref))
    print(matriz(term,ref))

(6, 7)
(6, 7)
campos ejemplo 4.0
[[1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]
 [1 1 1 0 1 1 1]
 [1 1 1 1 0 1 1]
 [1 1 1 1 1 1 0]
 [1 1 1 1 1 1 1]]
(12, 13)
(12, 13)
reconocibles irreconocible 3.0
[[1 0 0 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 0 1 1 1 1 1 1 1 1 0]
 [1 1 1 1 0 1 1 1 0 1 1 1 1]
 [1 1 1 1 1 0 1 0 1 1 1 1 1]
 [1 1 1 1 1 1 0 1 1 1 1 1 1]
 [1 1 1 1 1 0 1 0 1 1 1 1 1]
 [1 1 1 1 0 1 1 1 0 1 1 1 1]
 [0 1 1 1 1 1 1 1 1 0 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 0 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 0 1]
 [1 1 1 0 1 1 1 1 1 1 1 1 0]
 [1 1 1 1 1 1 1 1 1 1 1 1 1]]
(4, 5)
(4, 5)
hola holas 1.0
[[0 1 1 1 1]
 [1 0 1 1 1]
 [1 1 0 1 1]
 [1 1 1 0 1]]


In [68]:
def damerau_levenstein(term, ref):
   """
   Calcula la distancia de Damerau Levenshtein entre las cadenas term y ref
   """
   # Simula el infinito
   INF = len(term) + len(ref)

   mat = matriz(term, ref)
   res = np.zeros(shape=(len(term)+1,len(ref)+1))

   for i in range(0,len(term)+1):
      for j in range(0,len(ref)+1):
            if i==0 or j==0:
               res[i,j] = res[i,j] + i + j
            elif i == 1 or j == 1:
               res[i,j] =min(
                  mat[i-1,j-1] + res[i-1,j-1],
                  1 + res[i-1,j],
                  1 + res[i,j-1],
               )
            else:
               res[i,j] =min(
                  mat[i-1,j-1] + res[i-1,j-1],
                  1 + res[i-1,j],
                  1 + res[i,j-1],
                  1 + res[i-2,j-2] + (mat[i-2,j-1] + mat[i-1,j-2]) * INF
               )
   return res[len(term),len(ref)]